// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDeFerias.Bookings.Infrastructure.Context;

#nullable disable

namespace ToDeFerias.Bookings.Infrastructure.Migrations
{
    [DbContext(typeof(BookingContext))]
    partial class BookingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ToDeFerias.Bookings.Domain.Aggregates.BookingAggregate.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<byte>("Adults")
                        .HasColumnType("tinyint")
                        .HasColumnName("Adults");

                    b.Property<byte>("Children")
                        .HasColumnType("tinyint")
                        .HasColumnName("Children");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("Created");

                    b.Property<Guid>("HouseGuestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("LastUpdated")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("LastUpdated");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Status");

                    b.Property<decimal>("Value")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("Value");

                    b.HasKey("Id");

                    b.HasIndex("HouseGuestId");

                    b.HasIndex("RoomId");

                    b.ToTable("Bookings", (string)null);
                });

            modelBuilder.Entity("ToDeFerias.Bookings.Domain.Aggregates.BookingAggregate.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("Created");

                    b.Property<DateTimeOffset?>("LastUpdated")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("LastUpdated");

                    b.Property<byte>("Number")
                        .HasColumnType("tinyint")
                        .HasColumnName("Number");

                    b.Property<Guid>("RoomTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("Rooms", (string)null);
                });

            modelBuilder.Entity("ToDeFerias.Bookings.Domain.Aggregates.BookingAggregate.RoomType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("Created");

                    b.Property<DateTimeOffset?>("LastUpdated")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("LastUpdated");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("RoomTypes", (string)null);
                });

            modelBuilder.Entity("ToDeFerias.Bookings.Domain.Aggregates.HouseGuestAggregate.HouseGuest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("Created");

                    b.Property<DateTimeOffset?>("LastUpdated")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("LastUpdated");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("HouseGuests", (string)null);
                });

            modelBuilder.Entity("ToDeFerias.Bookings.Domain.Aggregates.BookingAggregate.Booking", b =>
                {
                    b.HasOne("ToDeFerias.Bookings.Domain.Aggregates.HouseGuestAggregate.HouseGuest", "HouseGuest")
                        .WithMany("Bookings")
                        .HasForeignKey("HouseGuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToDeFerias.Bookings.Domain.Aggregates.BookingAggregate.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ToDeFerias.Bookings.Domain.Aggregates.BookingAggregate.DateRangeBooking", "DateRange", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTimeOffset>("CheckIn")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("CheckIn");

                            b1.Property<DateTimeOffset>("CheckOut")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("CheckOut");

                            b1.HasKey("BookingId");

                            b1.ToTable("Bookings");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.Navigation("DateRange");

                    b.Navigation("HouseGuest");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("ToDeFerias.Bookings.Domain.Aggregates.BookingAggregate.Room", b =>
                {
                    b.HasOne("ToDeFerias.Bookings.Domain.Aggregates.BookingAggregate.RoomType", "Type")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("ToDeFerias.Bookings.Domain.Aggregates.HouseGuestAggregate.HouseGuest", b =>
                {
                    b.OwnsOne("ToDeFerias.Bookings.Domain.Aggregates.HouseGuestAggregate.Cpf", "Cpf", b1 =>
                        {
                            b1.Property<Guid>("HouseGuestId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("VARCHAR(255)")
                                .HasColumnName("Cpf");

                            b1.HasKey("HouseGuestId");

                            b1.ToTable("HouseGuests");

                            b1.WithOwner()
                                .HasForeignKey("HouseGuestId");
                        });

                    b.OwnsOne("ToDeFerias.Bookings.Domain.Aggregates.HouseGuestAggregate.DateOfBirth", "DateOfBirth", b1 =>
                        {
                            b1.Property<Guid>("HouseGuestId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTimeOffset>("Birthday")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("DateOfBirth");

                            b1.HasKey("HouseGuestId");

                            b1.ToTable("HouseGuests");

                            b1.WithOwner()
                                .HasForeignKey("HouseGuestId");
                        });

                    b.OwnsOne("ToDeFerias.Bookings.Domain.Aggregates.HouseGuestAggregate.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("HouseGuestId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasColumnType("VARCHAR(255)")
                                .HasColumnName("Email");

                            b1.HasKey("HouseGuestId");

                            b1.ToTable("HouseGuests");

                            b1.WithOwner()
                                .HasForeignKey("HouseGuestId");
                        });

                    b.Navigation("Cpf");

                    b.Navigation("DateOfBirth");

                    b.Navigation("Email");
                });

            modelBuilder.Entity("ToDeFerias.Bookings.Domain.Aggregates.BookingAggregate.Room", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("ToDeFerias.Bookings.Domain.Aggregates.BookingAggregate.RoomType", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("ToDeFerias.Bookings.Domain.Aggregates.HouseGuestAggregate.HouseGuest", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
